[package]
name = "chain-democracy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.17.1"
borsh = "0.10"
chrono = "0.4.31"


[lib]
crate-type = ["cdylib", "lib"]
